'use strict';
const E=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={meeting:'تقرير جلسة مجتمع التعلم المهني',visit:'استمارة تبادل زيارة صفية بين المعلمات',program:'تقرير تنفيذ برنامج مهني',growth:'سجل النمو المهني للمعلمة'};
const specialties={general:'جميع التخصصات',math:'الرياضيات',english:'اللغة الإنجليزية',arabic:'اللغة العربية',science:'العلوم',islamic:'الدراسات الإسلامية',social:'الدراسات الاجتماعية',digital:'المهارات الرقمية',chinese:'اللغة الصينية',arts:'التربية الفنية',pe:'التربية البدنية'};
const presets=[
 {id:'blank',group:'general',title:'نموذج فارغ',goals:'',agenda:''},
 {id:'ai',group:'general',title:'توظيف الذكاء الاصطناعي في التعليم',goals:'تحديد استخدام تعليمي يخدم نواتج التعلم.\nصياغة أوامر واضحة تتضمن المهمة والسياق ومعايير المخرج.\nتقويم دقة المخرجات وتعديلها مع مراعاة خصوصية الطالبات.',agenda:'عرض تطبيق مرتبط بالدرس.\nمقارنة مخرجات أوامر عامة وأوامر محددة.\nمناقشة معايير التحقق من المحتوى وتوثيق دور الطالبة.\nاقتراح مهمة تطبيقية وأداة لقياس أثرها.'},
 {id:'management',group:'general',title:'الإدارة الصفية الفاعلة',goals:'تحليل المواقف الصفية المتكررة وأسبابها.\nتطوير إجراءات واضحة لتنظيم المشاركة والانتقال بين الأنشطة.\nاختيار مؤشرات لمتابعة وقت التعلم والسلوك الصفي.',agenda:'مناقشة مواقف صفية دون ذكر بيانات شخصية.\nتبادل أساليب التعزيز وإدارة الوقت.\nتصميم إجراء صفي قابل للتطبيق والمتابعة.'},
 {id:'motivation',group:'general',title:'رفع دافعية الطالبات للتعلم',goals:'تحديد أسباب انخفاض المشاركة في المهام.\nتصميم أنشطة تراعي الاهتمامات وتتيح الاختيار.\nتحديد أداة لقياس المشاركة قبل التطبيق وبعده.',agenda:'تحليل شواهد المشاركة.\nمناقشة التعزيز والتغذية الراجعة وأهداف التعلم القصيرة.\nاقتراح نشاط وتحديد موعد مراجعة أثره.'},
 {id:'assessment',group:'general',title:'التقويم التكويني والتغذية الراجعة',goals:'تصميم أسئلة تكشف الفهم أثناء الدرس.\nتوظيف النتائج في تعديل التدريس.\nصياغة تغذية راجعة محددة تساعد الطالبة على التحسن.',agenda:'تحليل نماذج إجابات مجهّلة.\nتصميم بطاقة خروج ومعايير تصحيح.\nالاتفاق على آلية للاستجابة لصعوبات التعلم.'},
 {id:'differentiation',group:'general',title:'مراعاة الفروق الفردية',goals:'تحديد احتياجات التعلم من شواهد التقويم.\nتصميم مهام متدرجة تخدم الهدف نفسه.\nمتابعة تقدم كل مجموعة وفق معيار واضح.',agenda:'مراجعة شواهد الأداء.\nتبادل أمثلة للدعم والإثراء.\nتصميم مهام متدرجة وخطة متابعة.'},
 {id:'math-problem',group:'math',title:'تنمية مهارات حل المسألة الرياضية',goals:'تحليل الأخطاء في فهم المعطيات واختيار خطة الحل.\nتنمية التبرير الرياضي والتحقق من معقولية الإجابة.',agenda:'تحليل حلول طالبات بعد إخفاء الأسماء.\nمقارنة استراتيجيات الحل والتمثيلات.\nتصميم مهمة مشتركة وسلّم تقدير للتبرير.'},
 {id:'math-algebra',group:'math',title:'معالجة المفاهيم الخاطئة في الجبر',goals:'تحديد الأخطاء في التعامل مع المتغيرات والعمليات.\nتصميم أسئلة تشخيصية وأنشطة علاجية مناسبة.',agenda:'تحليل أمثلة للأخطاء الشائعة.\nاستخدام التمثيل اللفظي والعددي والرمزي.\nتحديد تقويم لاحق للتحقق من الإتقان.'},
 {id:'english-reading',group:'english',title:'تحسين الفهم القرائي باللغة الإنجليزية',goals:'تدريب الطالبات على تحديد الفكرة الرئيسة والتفاصيل.\nتنمية الاستدلال بالاعتماد على دليل من النص.\nتصميم مهام قراءة مناسبة للمستويات المختلفة.',agenda:'اختيار نص من الوحدة.\nتصميم أسئلة قبل القراءة وأثناءها وبعدها.\nمقارنة أداء الطالبات باستخدام معايير مشتركة.'},
 {id:'english-speaking',group:'english',title:'تنمية المحادثة والمفردات الإنجليزية',goals:'زيادة فرص استخدام المفردات في سياق ذي معنى.\nتنمية الطلاقة والتفاعل في مواقف تواصلية.\nتقديم تغذية راجعة تشجع المحاولة والتحسن.',agenda:'تصميم حوار ومهمة تبادل معلومات.\nمناقشة دعم الطالبات المترددات.\nإعداد بطاقة ملاحظة للطلاقة ووضوح المعنى والتفاعل.'},
 {id:'arabic-reading',group:'arabic',title:'الفهم القرائي وتحليل النصوص',goals:'تنمية تحديد الأفكار والعلاقات داخل النص.\nتوظيف الشواهد النصية في تفسير المعنى.',agenda:'تحليل نص من المقرر.\nتصميم أسئلة تتدرج من الفهم المباشر إلى الاستنتاج.\nتحديد معايير مشتركة للإجابة.'},
 {id:'science-inquiry',group:'science',title:'الاستقصاء والتفسير العلمي',goals:'صياغة أسئلة قابلة للاستقصاء.\nتنمية تفسير النتائج والاستدلال بالأدلة.',agenda:'تصميم تجربة مناسبة وآمنة.\nمناقشة المتغيرات وتسجيل البيانات.\nبناء معيار لتقويم التفسير العلمي.'},
 {id:'islamic-values',group:'islamic',title:'ربط المفاهيم الشرعية بالمواقف الحياتية',goals:'تعميق فهم المفهوم الشرعي من مصادر المقرر.\nتطبيق التعلم على مواقف حياتية مناسبة.',agenda:'تحليل مواقف تعليمية.\nصياغة أسئلة تدعم الفهم والتطبيق.\nاقتراح نشاط وتقويم مناسب.'},
 {id:'social-evidence',group:'social',title:'تحليل المصادر والخرائط',goals:'تنمية قراءة الخرائط واستخراج المعلومات.\nالتمييز بين الرأي والمعلومة المدعومة بالمصدر.',agenda:'اختيار خريطة ومصدر مناسبين.\nتصميم أسئلة للتحليل والمقارنة.\nالاتفاق على معايير للاستدلال.'},
 {id:'digital-safety',group:'digital',title:'المواطنة الرقمية وحل المشكلات',goals:'تنمية الاستخدام المسؤول للتقنية.\nتطبيق خطوات منظمة لحل مشكلة رقمية.',agenda:'مناقشة مواقف الخصوصية والأمان الرقمي.\nتصميم مهمة تطبيقية.\nتحديد معيار لتقويم خطوات الحل.'},
 {id:'chinese-communication',group:'chinese',title:'تعزيز تعلم اللغة الصينية',goals:'تنمية فهم المفردات والتعبيرات الأساسية.\nدعم النطق والممارسة التفاعلية.',agenda:'تبادل أنشطة سمعية وألعاب تعليمية.\nتصميم حوار قصير وورقة عمل.\nتحديد طريقة لملاحظة النطق والفهم.'},
 {id:'arts-creative',group:'arts',title:'تنمية التعبير الفني والإبداع',goals:'تنويع فرص التعبير باستخدام الخامات.\nتطوير معايير تصف الفكرة والتنفيذ والتأمل.',agenda:'عرض نماذج أعمال.\nمناقشة التغذية الراجعة.\nتصميم مهمة فنية ومعايير تقويم.'},
 {id:'pe-participation',group:'pe',title:'تعزيز المشاركة في التربية البدنية',goals:'تصميم أنشطة تناسب مستويات الأداء.\nتعزيز المشاركة الآمنة والتعاون.',agenda:'مناقشة تنظيم الأنشطة ومتطلبات السلامة.\nتكييف المهام حسب القدرات.\nتحديد مؤشرات للمشاركة والتقدم.'}
];
const visitItems=['تحقيق أهداف الدرس','التسلسل المنطقي لعرض الدرس','تنوع طرق التدريس ومناسبتها','تقديم ثقافة علمية مناسبة للدرس','تفعيل استراتيجيات التدريس','إدارة الصف','إدارة وقت الحصة','استخدام الوسائل المناسبة للدرس','استخدام السبورة وتنظيمها','تفعيل سجل المتابعة','جذب انتباه الطالبات وإثارة تفكيرهن','إجادة النقاش والحوار مع الطالبات ومعالجة إجاباتهن','استخدام عبارات التشجيع والتعزيز','تقويم الدرس في نهاية الحصة','تعدد أدوات التقويم'];
const definitions={
 meeting:[['topic','موضوع الجلسة'],['tools','أوعية وأدوات التطوير المهني'],['venue','مقر التنفيذ'],['target','نوع الفئة المستهدفة (التخصص)'],['date','اليوم / التاريخ'],['facilitator','اسم المنفذة'],['goals','أهداف الجلسة','area'],['results','نتائج الجلسة الفعلية','area']],
 visit:[['teacher','اسم المعلمة'],['grade','الصف'],['subject','المادة'],['classroom','الفصل'],['topic','موضوع الدرس'],['date','تاريخ الزيارة'],['visitor','اسم المعلمة الزائرة'],['positives','الإيجابيات','area'],['recommendations','مقترحات لتطوير الأداء (التوصيات)','area']],
 program:[['topic','موضوع البرنامج'],['generalGoal','الهدف العام','area'],['goals','الهدف الخاص','area'],['indicator','مؤشر الإنجاز','area'],['term','الفصل الدراسي'],['date','التاريخ'],['target','الفئة المستهدفة'],['count','عدد المستهدفات','number'],['duration','مدة البرنامج'],['method','أسلوب التنفيذ','method'],['agenda','أهداف البرنامج ومحاوره','area'],['positives','الإيجابيات الفعلية','area'],['recommendations','التوصيات','area'],['facilitator','اسم منفذة البرنامج'],['job','العمل المكلفة به']],
 growth:[['teacher','اسم المعلمة'],['specialty','التخصص']]
};
function blank(){return {fields:{},attendees:[{name:''}],courses:[{name:'',provider:'',date:'',days:'',type:'عام'}],ratings:Array(15).fill(''),notes:Array(15).fill(''),specialty:'general',preset:'blank'};}
const states=Object.fromEntries(Object.keys(names).map(k=>[k,blank()]));let kind=new URLSearchParams(location.search).get('form')||'meeting';if(!names[kind])kind='meeting';
const field=(id,label,type='text',value='')=>`<div class="field ${type==='area'?'full':''}"><label for="f_${id}">${esc(label)}</label>${type==='area'?`<textarea id="f_${id}" data-field="${id}" rows="3">${esc(value)}</textarea>`:type==='method'?`<select id="f_${id}" data-field="${id}"><option value="">اختاري</option>${['تدريب أقران','تبادل زيارات','تدريب مصغر','ورشة عمل','تجربة','لقاء / اجتماع','أخرى'].map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select>`:`<input id="f_${id}" data-field="${id}" type="${type==='number'?'number':'text'}" ${type==='number'?'min="0" step="1"':''} value="${esc(value)}" ${id==='date'?'placeholder="مثال: الثلاثاء 3 / 4 / 1448 هـ"':''}>`}</div>`;
Object.entries(names).forEach(([key,title])=>{const b=document.createElement('button');b.type='button';b.textContent=title;b.dataset.kind=key;b.onclick=()=>{kind=key;renderEditor();};E('#formTabs').append(b);});
Object.entries(specialties).forEach(([key,label])=>E('#specialty').add(new Option(label,key)));
function fillPresets(){const s=states[kind];E('#specialty').value=s.specialty;E('#preset').replaceChildren();presets.filter(p=>p.group==='general'||p.group===s.specialty).forEach(p=>E('#preset').add(new Option(p.title,p.id)));E('#preset').value=s.preset;if(E('#preset').selectedIndex<0){E('#preset').value='blank';s.preset='blank';}}
E('#specialty').onchange=()=>{states[kind].specialty=E('#specialty').value;fillPresets();};E('#preset').onchange=()=>states[kind].preset=E('#preset').value;
E('#applyPreset').onclick=()=>{const s=states[kind];const p=presets.find(x=>x.id===s.preset);if(!p||p.id==='blank'){E('#status').textContent='يمكنك تعبئة الحقول مباشرة. لمسح البيانات استخدمي زر مسح النموذج.';return;}if(['topic','goals','agenda','target'].some(x=>s.fields[x])&&!window.confirm('سيستبدل القالب الموضوع والأهداف والمحاور والفئة المستهدفة. هل تريدين تطبيقه؟'))return;Object.assign(s.fields,{topic:p.title,goals:p.goals,agenda:p.agenda,target:s.specialty==='general'?'معلمات جميع التخصصات':'معلمات '+specialties[s.specialty]});if(kind==='meeting')s.fields.tools='لقاء / اجتماع مهني';if(kind==='program'){s.fields.generalGoal='تطوير الممارسات التدريسية في مجال '+p.title;s.fields.method='ورشة عمل';}renderEditor();E('#status').textContent='تم تطبيق المقترح. راجعي الصياغة وأكملي بيانات التنفيذ والنتائج.';};
function renderEditor(){const s=states[kind];document.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.kind===kind));E('#editorTitle').textContent=names[kind];E('#presetPanel').hidden=!['meeting','program'].includes(kind);fillPresets();E('#status').textContent='';let h='<div class="fields">'+definitions[kind].map(([id,label,type])=>field(id,label,type,s.fields[id]||'')).join('')+'</div>';
 if(kind==='meeting')h+=`<fieldset><legend>الحاضرات (${s.attendees.length})</legend><p class="hint">أضيفي اسم كل حاضرة. تُترك التواقيع في النسخة المطبوعة.</p>${s.attendees.map((a,i)=>`<div class="repeat-row"><label for="a_${i}">اسم الحاضرة ${i+1}</label><input id="a_${i}" data-attendee="${i}" value="${esc(a.name)}"><button type="button" class="remove" data-remove-attendee="${i}">حذف الصف</button></div>`).join('')}<button type="button" class="secondary" data-add="attendee">إضافة حاضرة</button></fieldset>`;
 if(kind==='visit')h+=`<fieldset><legend>عناصر ملاحظة الدرس</legend>${visitItems.map((t,i)=>`<div class="evaluation"><label for="r_${i}">${i+1}. ${t}</label><select id="r_${i}" data-rating="${i}"><option value="">لم يُقيّم</option>${['جيد','متوسط','إلى حد ما','لم يُنفذ'].map(x=>`<option ${s.ratings[i]===x?'selected':''}>${x}</option>`).join('')}</select></div><label class="muted" for="n_${i}">ملاحظة العنصر ${i+1}</label><input id="n_${i}" data-note="${i}" value="${esc(s.notes[i])}">`).join('')}</fieldset>`;
 if(kind==='growth')h+=`<fieldset><legend>الدورات والبرامج المهنية</legend><p class="hint">أدرجي الدورات العامة والبرامج الخارجية التي حضرتِها، واحتفظي بصورة من مشهد الحضور لكل دورة.</p>${s.courses.map((c,i)=>`<div class="repeat-row"><strong>الدورة ${i+1}</strong><div class="fields">${[['name','اسم الدورة'],['provider','الجهة المنفذة'],['date','التاريخ'],['days','عدد الأيام']].map(([k,l])=>`<div class="field"><label for="c_${i}_${k}">${l}</label><input id="c_${i}_${k}" data-course="${i}" data-key="${k}" ${k==='days'?'type="number" min="1" step="1"':''} value="${esc(c[k])}"></div>`).join('')}<div class="field"><label for="c_${i}_type">نوع البرنامج</label><select id="c_${i}_type" data-course="${i}" data-key="type">${['عام','خارجي'].map(x=>`<option ${c.type===x?'selected':''}>${x}</option>`).join('')}</select></div></div><button type="button" class="remove" data-remove-course="${i}">حذف الدورة</button></div>`).join('')}<button type="button" class="secondary" data-add="course">إضافة دورة</button></fieldset>`;
 E('#electronicForm').innerHTML=h;renderPaper();}
E('#electronicForm').onsubmit=e=>e.preventDefault();E('#electronicForm').addEventListener('input',e=>{const d=e.target.dataset,s=states[kind];if(d.field)s.fields[d.field]=e.target.value;if(d.attendee!==undefined)s.attendees[+d.attendee].name=e.target.value;if(d.rating!==undefined)s.ratings[+d.rating]=e.target.value;if(d.note!==undefined)s.notes[+d.note]=e.target.value;if(d.course!==undefined)s.courses[+d.course][d.key]=e.target.value;renderPaper();});
E('#electronicForm').addEventListener('click',e=>{const d=e.target.dataset,s=states[kind];if(d.add==='attendee')s.attendees.push({name:''});else if(d.add==='course')s.courses.push({name:'',provider:'',date:'',days:'',type:'عام'});else if(d.removeAttendee!==undefined){if(s.attendees[+d.removeAttendee].name&&!window.confirm('حذف هذه الحاضرة؟'))return;s.attendees.splice(+d.removeAttendee,1);}else if(d.removeCourse!==undefined){if(Object.entries(s.courses[+d.removeCourse]).some(([k,v])=>k!=='type'&&v)&&!window.confirm('حذف بيانات هذه الدورة؟'))return;s.courses.splice(+d.removeCourse,1);}else return;renderEditor();});
const row=(label,value)=>`<tr><th scope="row" class="label">${esc(label)}</th><td>${esc(value)||'........................'}</td></tr>`;
const block=(label,value)=>`<section class="print-block"><h3>${esc(label)}</h3><p>${esc(value)||'................................................................'}</p></section>`;
function renderPaper(){const s=states[kind],v=s.fields;E('#paperTitle').textContent=names[kind];document.title=(v.topic||names[kind])+' - المتوسطة 216';let h='';
 if(kind==='meeting'){h='<table><tbody>'+[['موضوع الجلسة',v.topic],['أوعية وأدوات التطوير المهني',v.tools],['مقر التنفيذ',v.venue],['نوع الفئة المستهدفة (التخصص)',v.target],['عدد الحاضرات',s.attendees.filter(a=>a.name.trim()).length],['اليوم / التاريخ',v.date]].map(x=>row(...x)).join('')+'</tbody></table>'+block('أهداف الجلسة',v.goals);h+=block('نتائج الجلسة',v.results);h+='<table><thead><tr><th style="width:10%">م</th><th>الاسم (الحاضرات)</th><th style="width:28%">التوقيع</th></tr></thead><tbody>'+s.attendees.map((a,i)=>`<tr><td>${i+1}</td><td>${esc(a.name)||'................'}</td><td class="signature"></td></tr>`).join('')+'</tbody></table>'+block('المنفذة / الاسم',v.facilitator);}
 if(kind==='visit'){h='<table class="visit-info"><tbody>'+[['اسم المعلمة',v.teacher,'الصف',v.grade],['المادة',v.subject,'الفصل',v.classroom],['موضوع الدرس',v.topic,'تاريخ الزيارة',v.date]].map(([a,b,c,d])=>`<tr><th>${esc(a)}</th><td>${esc(b)||'................'}</td><th>${esc(c)}</th><td>${esc(d)||'................'}</td></tr>`).join('')+'</tbody></table><table class="visit-rubric"><colgroup><col style="width:6%"><col style="width:43%"><col style="width:9%"><col style="width:10%"><col style="width:11%"><col style="width:21%"></colgroup><thead><tr><th>م</th><th>العناصر</th><th>جيد</th><th>متوسط</th><th>إلى حد ما</th><th>لم يُنفذ / ملاحظات</th></tr></thead><tbody>'+visitItems.map((t,i)=>`<tr><td>${i+1}</td><td>${t}</td><td>${s.ratings[i]==='جيد'?'✓':''}</td><td>${s.ratings[i]==='متوسط'?'✓':''}</td><td>${s.ratings[i]==='إلى حد ما'?'✓':''}</td><td>${s.ratings[i]==='لم يُنفذ'?'لم يُنفذ':''}${s.ratings[i]==='لم يُنفذ'&&s.notes[i]?' — ':''}${esc(s.notes[i])}</td></tr>`).join('')+'</tbody></table>'+block('الإيجابيات',v.positives)+block('مقترحات لتطوير الأداء (التوصيات)',v.recommendations)+block('المعلمة الزائرة / التوقيع',(v.visitor||'................')+'\nالتوقيع: ........................');}

 if(kind==='program'){h='<table><tbody>'+definitions.program.filter(x=>!['facilitator','job'].includes(x[0])).map(([id,l])=>row(l,v[id])).join('')+'</tbody></table><table><thead><tr><th>اسم منفذة البرنامج</th><th>العمل المكلفة به</th><th>التوقيع</th></tr></thead><tbody><tr><td>'+esc(v.facilitator)+'</td><td>'+esc(v.job)+'</td><td class="signature"></td></tr></tbody></table>';}
 if(kind==='growth'){h='<table><tbody>'+row('اسم المعلمة',v.teacher)+row('التخصص',v.specialty)+'</tbody></table>';for(const type of ['عام','خارجي']){const list=s.courses.filter(c=>c.type===type);h+=`<h3>${type==='عام'?'الدورات العامة':'البرامج المهنية الخارجية (كمستفيدة)'}</h3><table><thead><tr><th style="width:8%">م</th><th>اسم الدورة</th><th>الجهة المنفذة</th><th style="width:21%">التاريخ</th><th style="width:13%">عدد الأيام</th></tr></thead><tbody>${list.map((c,i)=>`<tr><td>${i+1}</td><td>${esc(c.name)}</td><td>${esc(c.provider)}</td><td>${esc(c.date)}</td><td>${esc(c.days)}</td></tr>`).join('')||'<tr><td colspan="5">لم تُدرج دورات.</td></tr>'}</tbody></table>`;}h+='<p class="muted">يُرفق مشهد الحضور لكل دورة ضمن شواهد النمو المهني.</p>';}
 E('#paperBody').innerHTML=h;}
E('#clearForm').onclick=()=>{if(!window.confirm('مسح جميع بيانات هذا النموذج؟ لن تتأثر النماذج الأخرى.'))return;states[kind]=blank();renderEditor();};
E('#printForm').onclick=()=>{if(!E('#electronicForm').reportValidity())return;window.print();};
renderEditor();
